version: '3.8'
services:
  app:
    container_name: nhnotifier
    image: nhnotifier:latest
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
    restart: always